# Generated by Django 4.2 on 2023-05-01 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
