# Generated by Django 4.2 on 2023-05-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('group', '0002_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
